# Generated by Django 4.0.6 on 2024-01-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_add_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='receiver',
            new_name='addreceiver',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='sender',
            new_name='addsender',
        ),
    ]
