# Generated by Django 4.0.6 on 2024-01-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_receiver_add_addreceiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsrecieved',
            name='randoms',
            field=models.IntegerField(null=True),
        ),
    ]
